apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: varodrig-poi-map-app-dev
  annotations:
    argocd/app-name: varodrig-poi-map-app-dev
    backstage.io/kubernetes-id: varodrig-poi-map-app-dev
    backstage.io/kubernetes-namespace: varodrig
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=varodrig-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/varodrig-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/varodrig/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/varodrig/deployments/varodrig-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/varodrig-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://varodrig-poi-map-app-varodrig.apps.rosa916.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/varodrig"
  system: workshop-system-varodrig
  consumesApis:
    - gateway-api-varodrig
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-varodrig
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/varodrig"
